# Generated by Django 4.2.5 on 2024-03-26 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0005_rename_object_temp_sensordata_body_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='heart_rate',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensordata',
            name='risk',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
