# Generated by Django 4.2.5 on 2023-11-20 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0004_alter_sensordata_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensordata',
            old_name='object_temp',
            new_name='body_temp',
        ),
    ]
