# Generated by Django 4.2.5 on 2024-04-09 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0009_notification_is_read'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
